// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int32
	Name      string
	Email     string
	Username  string
	Password  string
	Image     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
